# Generated by Django 3.2.19 on 2023-06-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0036_add_attachment_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='multiselect',
            field=models.BooleanField(default=False, help_text='For list fields only.', verbose_name='Enable multiple selections?'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='widget_type',
            field=models.CharField(choices=[('dropdown', 'Dropdown'), ('radio_or_checkbox', 'Radio buttons or checkboxes')], default='dropdown', help_text='For list fields only.', max_length=20, null=True, verbose_name='Widget Choice'),
        ),
    ]
