# Generated by Django 3.2.19 on 2023-06-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0037_auto_20230612_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='hidden',
            field=models.BooleanField(default=False, help_text='This field will be hidden from the user. Use a custom public ticket form class to assign a value.', verbose_name='Hidden?'),
        ),
    ]
