# Generated by Django 3.2.19 on 2023-09-12 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0038_customfield_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='submitter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Submitter'),
        ),
    ]
