# Generated by Django 3.2.23 on 2024-01-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0039_auto_20230912_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='data_type',
            field=models.CharField(choices=[('varchar', 'Character (single line)'), ('text', 'Text (multi-line)'), ('integer', 'Integer'), ('positiveinteger', 'Positive Integer'), ('decimal', 'Decimal'), ('list', 'List'), ('boolean', 'Boolean (checkbox yes/no)'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('email', 'E-Mail Address'), ('url', 'URL'), ('ipaddress', 'IP Address'), ('slug', 'Slug')], help_text='Allows you to restrict the data entered into this field', max_length=100, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='hidden',
            field=models.BooleanField(default=False, help_text='This field will be hidden from the user. A value can be assigned in your custom code.', verbose_name='Hidden?'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='label',
            field=models.CharField(help_text='The display label for this field', max_length=255, verbose_name='Label'),
        ),
    ]
